version: '3'

# usage
# can't quite figure out how to define env dynamically within taskfile
# hence, need to set at shell before running task command

# $env:TODAY=$((Get-Date).ToString('yyyy-MM-dd'))
# $env:WORKING_DIR=$(pwd)
# task dl-all

# improvment
# 7z the directory
# delete the directory

vars:
  # Workaround for error when calling `Move-Item` in cmds - "Move-Item": executable file not found in $PATH
  # See https://github.com/go-task/task/issues/892
  SHELL: '{{if eq .OS "Windows_NT"}}pwsh{{end}}'

tasks:
  dl-all:
    cmds:
      - echo $TODAY
      - echo $WORKING_DIR
      - echo "creating directory"
      - '{{.SHELL}} -Command New-Item -ItemType Directory $TODAY -Force'
      - echo "starting downloads"
      - task: dl-apps
      - task: dl-gh
      - task: dl-helm
      - task: dl-pw
      - task: dl-ip
      - task: dl-vsc
      - task: dl-wg
      - echo "download completed - $TODAY"
  dl-apps:
    platforms: [windows]
    dir: /apps
    vars:
      APP_DL_DIR: $WORKING_DIR\\apps\\_applications
    cmds:
      - pwsh -File apps-downloads.ps1
      - '{{.SHELL}} -Command Move-Item -Path {{.APP_DL_DIR}} -Destination $WORKING_DIR\\$TODAY'
  dl-gh:
    platforms: [windows]
    dir: /github
    vars:
      GH_DL_DIR: $WORKING_DIR\\github\\_github_applications
    cmds:
      - pwsh -File github-downloads.ps1
      - '{{.SHELL}} -Command Move-Item -Path {{.GH_DL_DIR}} -Destination $WORKING_DIR\\$TODAY'
  dl-helm:
    platforms: [windows]
    dir: /helm
    vars:
      HELM_DL_DIR: $WORKING_DIR\\helm\\_helmcharts
    cmds:
      - pwsh -File helm-downloads.ps1
      - '{{.SHELL}} -Command Move-Item -Path {{.HELM_DL_DIR}} -Destination $WORKING_DIR\\$TODAY'
  dl-pw:
    platforms: [windows]
    dir: /playwright
    vars:
      PW_DL_DIR: $WORKING_DIR\\playwright\\_playwright
    cmds:
      - pwsh -File playwright-downloads.ps1
      - '{{.SHELL}} -Command Move-Item -Path {{.PW_DL_DIR}} -Destination $WORKING_DIR\\$TODAY'
  dl-ip:
    platforms: [windows]
    dir: /plugins/intellij
    vars:
      IP_DL_DIR: $WORKING_DIR\\plugins\\intellij
    cmds:
      - pwsh -File intellij-plugin-downloads.ps1 -version 2023.1.3 -build 231.9161.38
      - '{{.SHELL}} -Command Move-Item -Path {{.IP_DL_DIR}}\\_intellij_plugins_2023.1.3 -Destination $WORKING_DIR\\$TODAY'
      - pwsh -File intellij-plugin-downloads.ps1 -version 2023.2.5 -build 232.10227.8
      - '{{.SHELL}} -Command Move-Item -Path {{.IP_DL_DIR}}\\_intellij_plugins_2023.2.5 -Destination $WORKING_DIR\\$TODAY'
      - pwsh -File intellij-plugin-downloads.ps1 -version 2023.3.4 -build 233.14475.28
      - '{{.SHELL}} -Command Move-Item -Path {{.IP_DL_DIR}}\\_intellij_plugins_2023.3.4 -Destination $WORKING_DIR\\$TODAY'
  dl-vsc:
    platforms: [windows]
    dir: /plugins/vscode
    vars:
      VSC_MODEL_DL_DIR: $WORKING_DIR\\plugins\\vscode\\_vscode_models
      VSC_PLUGIN_DL_DIR: $WORKING_DIR\\plugins\\vscode\\_vscode_plugins
    cmds:
      - pwsh -File vscode-models-downloads.ps1 -username joseph -version 1.2.30
      - '{{.SHELL}} -Command Move-Item -Path {{.VSC_MODEL_DL_DIR}} -Destination $WORKING_DIR\\$TODAY'
      - pwsh -File vscode-plugin-downloads.ps1
      - '{{.SHELL}} -Command Move-Item -Path {{.VSC_PLUGIN_DL_DIR}} -Destination $WORKING_DIR\\$TODAY'
  dl-wg:
    platforms: [windows]
    dir: /winget
    vars:
      WG_DL_DIR: $WORKING_DIR\\winget\\_winget_applications
    cmds:
      - pwsh -File winget-downloads.ps1
      - '{{.SHELL}} -Command Move-Item -Path {{.WG_DL_DIR}} -Destination $WORKING_DIR\\$TODAY'