version: '3'

vars:
  ENV: '{{.ENV | default "prod"}}'
  TODAY: '{{now | date "2006-01-02"}}'
  WORKING_DIR: '{{.PWD}}'
  SHELL: '{{if eq .OS "Windows_NT"}}pwsh{{end}}'

tasks:
  dl-all:
    desc: Run all download tasks.
    cmds:
      - '{{.SHELL}} -Command New-Item -ItemType Directory {{.TODAY}} -Force'
      - task: dl-apps
      - task: dl-intellij-drivers
      - task: dl-gh
      - task: dl-helm
      - task: dl-pw
      - task: dl-chrome
      - task: dl-ip
      - task: dl-wg
      - task: dl-duck

  archive:
    desc: Compress the dated download directory.
    cmds:
      - 7z a -t7z {{.TODAY}}.7z {{.TODAY}}

  cleanup:
    desc: Remove the dated download directory.
    cmds:
      - '{{.SHELL}} -Command Remove-Item -Recurse -Force {{.TODAY}}'

  check-apps:
    desc: Check custom applications for updates.
    dir: apps
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File check-updates.ps1'

  dl-apps:
    dir: apps
    vars:
      APP_CONFIG: '{{if eq .ENV "test"}}custom-applications-test.json{{else}}custom-applications.json{{end}}'
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File apps-downloads.ps1 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\apps\_applications" -JsonFile "{{.APP_CONFIG}}"'

  dl-intellij-drivers:
    dir: drivers/intellij
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File drivers-downloads.ps1 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\drivers\intellij\_intellij_jdbc_drivers"'

  dl-gh:
    dir: github
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File github-downloads.ps1 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\github\_github_applications"'

  dl-helm:
    dir: helm
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File helm-downloads.ps1 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\helm\_helmcharts"'

  dl-pw:
    dir: playwright
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File playwright-downloads.ps1 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\playwright\_playwright"'

  dl-chrome:
    dir: plugins/chrome
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File chrome-plugin-downloads.ps1 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\plugins\chrome\_chrome"'

  dl-duck:
    dir: plugins/duckdb
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File duckdb-extensions-downloads.ps1 -version 1.5.2 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\plugins\duckdb\_duckdb_extensions_1.5.2"'

  dl-ip:
    dir: plugins/intellij
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File intellij-plugin-downloads.ps1 -version 2026.1.2 -build 261.24374.151 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\plugins\intellij\_intellij_plugins_2026.1.2"'

  dl-wg:
    dir: winget
    cmds:
      - '{{.SHELL}} -ExecutionPolicy Bypass -File winget-downloads.ps1 -DestDir "{{.WORKING_DIR}}\{{.TODAY}}\winget\_winget_applications"'
